name: Send Inactive User Emails

on:
  schedule:
    - cron: '0 19 */7 * *'  # Every 7 days at 7 PM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-emails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install firebase-admin
      
    - name: Run inactive users emailer
      run: node inactive-users-emailer.js
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
